# Use root/example as user/password credentials
version: '3.9'
services:
  my-sql: 
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: freelancerproject
      MYSQL_USER: root
      MYSQL_PASSWORD: null
    volumes:
      - ./data/mysql:/var/lib/mysql